paths:
  .github/workflows/release.yml:
    ignore:
      # reason: GitHub supports queue: max, but actionlint does not recognize the queue key.
      # Remove this exception when https://github.com/rhysd/actionlint/issues/657 is resolved.
      - '^unexpected key "queue" for "concurrency" section\. expected one of "cancel-in-progress", "group"$'
